<?xml version="1.0" encoding="utf-8"?>
<SerializeableGameProject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <name>testgp1</name>
  <items>
    <SerializeableGameItem xsi:type="SerializeableGameSprite">
      <name>SprPlayer</name>
      <pathes>
        <string>\res\SprPlayer_strip2.png</string>
      </pathes>
      <numOfImages>2</numOfImages>
      <originX>16</originX>
      <originY>16</originY>
      <preciseMask>false</preciseMask>
      <separateMask>false</separateMask>
      <maskBounding_auto>false</maskBounding_auto>
      <maskBounding_fullImage>true</maskBounding_fullImage>
      <maskBounding_manual>false</maskBounding_manual>
      <maskTop>0</maskTop>
      <maskRight>31</maskRight>
      <maskBottom>31</maskBottom>
      <maskLeft>0</maskLeft>
      <maskAlphaTolerance>0</maskAlphaTolerance>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameSprite">
      <name>SprWall</name>
      <pathes>
        <string>\res\SprWall.png</string>
      </pathes>
      <numOfImages>1</numOfImages>
      <originX>0</originX>
      <originY>0</originY>
      <preciseMask>false</preciseMask>
      <separateMask>false</separateMask>
      <maskBounding_auto>false</maskBounding_auto>
      <maskBounding_fullImage>true</maskBounding_fullImage>
      <maskBounding_manual>false</maskBounding_manual>
      <maskTop>0</maskTop>
      <maskRight>31</maskRight>
      <maskBottom>31</maskBottom>
      <maskLeft>0</maskLeft>
      <maskAlphaTolerance>0</maskAlphaTolerance>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameSprite">
      <name>SprSpikes</name>
      <pathes>
        <string>\res\SprSpikes.png</string>
      </pathes>
      <numOfImages>1</numOfImages>
      <originX>0</originX>
      <originY>0</originY>
      <preciseMask>false</preciseMask>
      <separateMask>false</separateMask>
      <maskBounding_auto>false</maskBounding_auto>
      <maskBounding_fullImage>true</maskBounding_fullImage>
      <maskBounding_manual>false</maskBounding_manual>
      <maskTop>0</maskTop>
      <maskRight>31</maskRight>
      <maskBottom>31</maskBottom>
      <maskLeft>0</maskLeft>
      <maskAlphaTolerance>0</maskAlphaTolerance>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameSprite">
      <name>SprKey</name>
      <pathes>
        <string>\res\SprKey.png</string>
      </pathes>
      <numOfImages>1</numOfImages>
      <originX>0</originX>
      <originY>0</originY>
      <preciseMask>false</preciseMask>
      <separateMask>false</separateMask>
      <maskBounding_auto>true</maskBounding_auto>
      <maskBounding_fullImage>false</maskBounding_fullImage>
      <maskBounding_manual>false</maskBounding_manual>
      <maskTop>10</maskTop>
      <maskRight>30</maskRight>
      <maskBottom>20</maskBottom>
      <maskLeft>1</maskLeft>
      <maskAlphaTolerance>0</maskAlphaTolerance>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameSprite">
      <name>SprPortal</name>
      <pathes>
        <string>\res\SprPortal.png</string>
      </pathes>
      <numOfImages>1</numOfImages>
      <originX>0</originX>
      <originY>0</originY>
      <preciseMask>false</preciseMask>
      <separateMask>false</separateMask>
      <maskBounding_auto>true</maskBounding_auto>
      <maskBounding_fullImage>false</maskBounding_fullImage>
      <maskBounding_manual>false</maskBounding_manual>
      <maskTop>2</maskTop>
      <maskRight>29</maskRight>
      <maskBottom>30</maskBottom>
      <maskLeft>3</maskLeft>
      <maskAlphaTolerance>0</maskAlphaTolerance>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameSound">
      <name>BgMusic</name>
      <path>\res\BgMusic.mp3</path>
      <volume>1</volume>
      <pan>0</pan>
      <patch>0</patch>
      <type>BackgroundMusic</type>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameSound">
      <name>SomeSnd</name>
      <path>\res\SomeSnd.wav</path>
      <volume>1</volume>
      <pan>0</pan>
      <patch>0</patch>
      <type>SoundEffect</type>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGamePath">
      <name>Path0</name>
      <points>
        <PathPoint>
          <x>144</x>
          <y>176</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>1072</x>
          <y>192</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>336</x>
          <y>368</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>320</x>
          <y>96</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>624</x>
          <y>464</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>0</x>
          <y>0</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>96</x>
          <y>304</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>96</x>
          <y>208</y>
          <speed>100</speed>
        </PathPoint>
        <PathPoint>
          <x>192</x>
          <y>272</y>
          <speed>100</speed>
        </PathPoint>
      </points>
      <close>true</close>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameFont">
      <font>
        <name>Font0</name>
        <family>Arial</family>
        <size>12</size>
        <bold>false</bold>
        <italic>false</italic>
      </font>
      <ttf>C:\Users\איתן\Desktop\testgp1\res\fonts\Font0.ttf</ttf>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameScript">
      <name>Global</name>
      <path>\Global.cs</path>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameObject">
      <name>ObjPlayer</name>
      <sprite>SprPlayer</sprite>
      <solid>false</solid>
      <depth>0</depth>
      <events>
        <EventScripts>
          <Scripts>
            <EventScript>
              <Script>/// start music
playback = playSound(Sounds.BgMusic, true)</Script>
              <Description>start music</Description>
            </EventScript>
            <EventScript>
              <Script>/// init
imageSpeed = 20</Script>
              <Description>init</Description>
            </EventScript>
          </Scripts>
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts>
            <EventScript>
              <Script>/// movements

//keyboard input
var movespeed = 0

if (keyDown(Keys.right))
{
    movespeed = 5
}

if (keyDown(Keys.left))
{
    movespeed = -5
}

if keyDown(Keys.space)
{
    playback.pause()
}

if keyDown(Keys.x)
{
    imageAngle += 1
}

if keyDown(Keys.z)
{
    imageAngle -= 1
}


// move

if placeFree(x + movespeed, y) == false
{
   while placeFree(x+sign(movespeed),y)
   {
       x += sign(movespeed)
   }
}
else
{
    x += movespeed
}


//gravity
fallspeed += gra

if placeFree(x,y+fallspeed) == false
{
    while placeFree(x, y + sign(fallspeed))
    {
        y += sign(fallspeed)
    }
    fallspeed = 0
}

y += fallspeed

//jump
if keyDown(Keys.up)
{
    if placeFree(x, y + 1) == false
    {
        fallspeed -= jumpspeed
    }
}

// game logic
if placeMeeting(x, y, ObjKey.i)
{
    Global.takeKey = true
    ObjKey.i.destroy()
}
else { if placeMeeting(x, y, ObjPortal.i) &amp; Global.takeKey
{
    goToNextRoom()
}
}

if placeMeeting(x, y, &lt;ObjSpikes&gt;)
{
    Global.takeKey = false
    restartRoom()
}</Script>
              <Description>movements</Description>
            </EventScript>
          </Scripts>
          <Event>Step</Event>
        </EventScripts>
      </events>
      <extraProperties>
        <ObjectProperty>
          <Name>fallspeed</Name>
          <Type>Number</Type>
          <InitValueCode>0</InitValueCode>
          <Constant>false</Constant>
          <Private>false</Private>
          <Nullable>false</Nullable>
        </ObjectProperty>
        <ObjectProperty>
          <Name>gra</Name>
          <Type>Number</Type>
          <InitValueCode>1</InitValueCode>
          <Constant>false</Constant>
          <Private>false</Private>
          <Nullable>true</Nullable>
        </ObjectProperty>
        <ObjectProperty>
          <Name>jumpspeed</Name>
          <Type>Number</Type>
          <InitValueCode>15</InitValueCode>
          <Constant>false</Constant>
          <Private>false</Private>
          <Nullable>false</Nullable>
        </ObjectProperty>
        <ObjectProperty>
          <Name>playback</Name>
          <Type>Any</Type>
          <InitValueCode>null</InitValueCode>
          <Constant>false</Constant>
          <Private>false</Private>
          <Nullable>true</Nullable>
        </ObjectProperty>
        <ObjectProperty>
          <Name>fcounter</Name>
          <Type>Number</Type>
          <InitValueCode>0</InitValueCode>
          <Constant>false</Constant>
          <Private>false</Private>
          <Nullable>false</Nullable>
        </ObjectProperty>
        <ObjectProperty>
          <Name>angle</Name>
          <Type>Number</Type>
          <InitValueCode>0</InitValueCode>
          <Constant>false</Constant>
          <Private>false</Private>
          <Nullable>false</Nullable>
        </ObjectProperty>
      </extraProperties>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameObject">
      <name>ObjWall</name>
      <sprite>SprWall</sprite>
      <solid>true</solid>
      <depth>0</depth>
      <events>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
      </events>
      <extraProperties />
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameObject">
      <name>ObjSpikes</name>
      <sprite>SprSpikes</sprite>
      <solid>false</solid>
      <depth>0</depth>
      <events>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
      </events>
      <extraProperties />
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameObject">
      <name>ObjKey</name>
      <sprite>SprKey</sprite>
      <solid>false</solid>
      <depth>0</depth>
      <events>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
      </events>
      <extraProperties />
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameObject">
      <name>ObjPortal</name>
      <sprite>SprPortal</sprite>
      <solid>false</solid>
      <depth>0</depth>
      <events>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
        <EventScripts>
          <Scripts />
          <Event>Create</Event>
        </EventScripts>
      </events>
      <extraProperties />
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameRoom">
      <name>Room0</name>
      <index>0</index>
      <backColor>
        <A>255</A>
        <R>192</R>
        <G>192</G>
        <B>192</B>
      </backColor>
      <backgrounds>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
      </backgrounds>
      <scriptPath>\Room0.cs</scriptPath>
      <width>900</width>
      <height>480</height>
      <speed>30</speed>
      <persistent>false</persistent>
      <caption>Level 1</caption>
      <objects>
        <SerializeableRoomObject>
          <id>R0INST1000</id>
          <x>0</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1001</id>
          <x>0</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1002</id>
          <x>0</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1003</id>
          <x>0</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1004</id>
          <x>0</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1005</id>
          <x>0</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1006</id>
          <x>0</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1007</id>
          <x>0</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1008</id>
          <x>0</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1009</id>
          <x>0</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1010</id>
          <x>0</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1011</id>
          <x>0</x>
          <y>352</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1012</id>
          <x>0</x>
          <y>384</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1013</id>
          <x>0</x>
          <y>416</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1014</id>
          <x>0</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1015</id>
          <x>32</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1016</id>
          <x>64</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1017</id>
          <x>96</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1018</id>
          <x>128</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1019</id>
          <x>160</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1020</id>
          <x>192</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1021</id>
          <x>224</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1022</id>
          <x>256</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1023</id>
          <x>288</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1024</id>
          <x>320</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1025</id>
          <x>352</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1026</id>
          <x>384</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1027</id>
          <x>416</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1028</id>
          <x>448</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1029</id>
          <x>480</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1030</id>
          <x>512</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1031</id>
          <x>544</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1032</id>
          <x>576</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1033</id>
          <x>608</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1050</id>
          <x>576</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1051</id>
          <x>544</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1052</id>
          <x>512</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1053</id>
          <x>480</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1054</id>
          <x>448</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1055</id>
          <x>416</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1056</id>
          <x>384</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1057</id>
          <x>352</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1058</id>
          <x>320</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1064</id>
          <x>128</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1065</id>
          <x>96</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1066</id>
          <x>64</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1067</id>
          <x>32</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1068</id>
          <x>160</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1069</id>
          <x>192</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1070</id>
          <x>224</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1071</id>
          <x>256</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1073</id>
          <x>288</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1000</id>
          <x>320</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1001</id>
          <x>352</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1002</id>
          <x>288</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1004</id>
          <x>256</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1005</id>
          <x>384</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1006</id>
          <x>416</x>
          <y>416</y>
          <obj>ObjSpikes</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1007</id>
          <x>448</x>
          <y>416</y>
          <obj>ObjSpikes</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1008</id>
          <x>480</x>
          <y>416</y>
          <obj>ObjSpikes</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1009</id>
          <x>160</x>
          <y>416</y>
          <obj>ObjSpikes</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1010</id>
          <x>192</x>
          <y>416</y>
          <obj>ObjSpikes</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1011</id>
          <x>224</x>
          <y>416</y>
          <obj>ObjSpikes</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1012</id>
          <x>320</x>
          <y>416</y>
          <obj>ObjKey</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1013</id>
          <x>320</x>
          <y>352</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1014</id>
          <x>320</x>
          <y>320</y>
          <obj>ObjPortal</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1000</id>
          <x>320</x>
          <y>96</y>
          <obj>ObjPlayer</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1000</id>
          <x>640</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1001</id>
          <x>672</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1002</id>
          <x>704</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1003</id>
          <x>736</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1004</id>
          <x>768</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1005</id>
          <x>800</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1006</id>
          <x>832</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1007</id>
          <x>864</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1008</id>
          <x>864</x>
          <y>416</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1009</id>
          <x>864</x>
          <y>384</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1010</id>
          <x>864</x>
          <y>352</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1011</id>
          <x>864</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1012</id>
          <x>864</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1013</id>
          <x>864</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1014</id>
          <x>864</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1015</id>
          <x>864</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1016</id>
          <x>864</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1017</id>
          <x>864</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1018</id>
          <x>864</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1019</id>
          <x>864</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1020</id>
          <x>864</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1021</id>
          <x>864</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1022</id>
          <x>832</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1023</id>
          <x>800</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1024</id>
          <x>768</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1025</id>
          <x>736</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1026</id>
          <x>704</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1027</id>
          <x>672</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1028</id>
          <x>640</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R0INST1030</id>
          <x>608</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
      </objects>
      <enableViews>true</enableViews>
      <views>
        <SerializeableRoomView>
          <visible>true</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow>ObjPlayer</objFollow>
          <followHBor>320</followHBor>
          <followVBor>240</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
      </views>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameRoom">
      <name>Room1</name>
      <index>1</index>
      <backColor>
        <A>255</A>
        <R>192</R>
        <G>192</G>
        <B>192</B>
      </backColor>
      <backgrounds>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
      </backgrounds>
      <scriptPath>\Room1.cs</scriptPath>
      <width>640</width>
      <height>480</height>
      <speed>30</speed>
      <persistent>false</persistent>
      <caption>Level 2</caption>
      <objects>
        <SerializeableRoomObject>
          <id>R1INST1000</id>
          <x>384</x>
          <y>160</y>
          <obj>ObjPlayer</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1000</id>
          <x>0</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1001</id>
          <x>0</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1002</id>
          <x>0</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1003</id>
          <x>0</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1004</id>
          <x>0</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1005</id>
          <x>0</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1006</id>
          <x>0</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1007</id>
          <x>0</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1008</id>
          <x>0</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1009</id>
          <x>0</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1013</id>
          <x>0</x>
          <y>352</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1014</id>
          <x>0</x>
          <y>384</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1015</id>
          <x>0</x>
          <y>416</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1016</id>
          <x>0</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1017</id>
          <x>32</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1018</id>
          <x>64</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1019</id>
          <x>96</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1020</id>
          <x>128</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1021</id>
          <x>160</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1022</id>
          <x>192</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1023</id>
          <x>224</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1024</id>
          <x>256</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1025</id>
          <x>288</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1026</id>
          <x>320</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1027</id>
          <x>352</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1028</id>
          <x>384</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1029</id>
          <x>416</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1030</id>
          <x>448</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1031</id>
          <x>480</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1032</id>
          <x>512</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1033</id>
          <x>544</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1034</id>
          <x>576</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1035</id>
          <x>608</x>
          <y>448</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1036</id>
          <x>608</x>
          <y>416</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1037</id>
          <x>608</x>
          <y>384</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1038</id>
          <x>608</x>
          <y>352</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1039</id>
          <x>608</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1040</id>
          <x>608</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1041</id>
          <x>608</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1042</id>
          <x>608</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1043</id>
          <x>608</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1044</id>
          <x>608</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1045</id>
          <x>608</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1046</id>
          <x>608</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1047</id>
          <x>608</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1048</id>
          <x>608</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1049</id>
          <x>608</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1050</id>
          <x>576</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1051</id>
          <x>544</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1052</id>
          <x>512</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1053</id>
          <x>480</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1054</id>
          <x>448</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1055</id>
          <x>416</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1056</id>
          <x>384</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1057</id>
          <x>352</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1058</id>
          <x>320</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1059</id>
          <x>288</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1060</id>
          <x>256</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1061</id>
          <x>224</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1062</id>
          <x>192</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1063</id>
          <x>160</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1064</id>
          <x>128</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1065</id>
          <x>96</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1066</id>
          <x>64</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1068</id>
          <x>32</x>
          <y>0</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1069</id>
          <x>0</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1070</id>
          <x>256</x>
          <y>160</y>
          <obj>ObjPlayer</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1071</id>
          <x>320</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1072</id>
          <x>320</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1073</id>
          <x>320</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1074</id>
          <x>320</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1075</id>
          <x>320</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1076</id>
          <x>320</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1077</id>
          <x>320</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1078</id>
          <x>320</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1079</id>
          <x>320</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1080</id>
          <x>320</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1081</id>
          <x>320</x>
          <y>352</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1082</id>
          <x>320</x>
          <y>384</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R1INST1084</id>
          <x>320</x>
          <y>416</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
      </objects>
      <enableViews>false</enableViews>
      <views>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
      </views>
    </SerializeableGameItem>
    <SerializeableGameItem xsi:type="SerializeableGameRoom">
      <name>RmEnd</name>
      <index>2</index>
      <backColor>
        <A>255</A>
        <R>192</R>
        <G>192</G>
        <B>192</B>
      </backColor>
      <backgrounds>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
        <RoomBackground>
          <visible>false</visible>
          <foreground>false</foreground>
          <tileHor>true</tileHor>
          <tileVer>true</tileVer>
          <x>0</x>
          <y>0</y>
          <stretch>false</stretch>
          <horSpd>0</horSpd>
          <verSpd>0</verSpd>
        </RoomBackground>
      </backgrounds>
      <scriptPath>\RmEnd.cs</scriptPath>
      <width>850</width>
      <height>480</height>
      <speed>30</speed>
      <persistent>false</persistent>
      <caption>Game Over</caption>
      <objects>
        <SerializeableRoomObject>
          <id>R2INST1000</id>
          <x>192</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1001</id>
          <x>160</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1002</id>
          <x>128</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1003</id>
          <x>96</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1004</id>
          <x>64</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1005</id>
          <x>64</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1006</id>
          <x>64</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1007</id>
          <x>64</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1008</id>
          <x>64</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1009</id>
          <x>64</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1010</id>
          <x>64</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1011</id>
          <x>64</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1012</id>
          <x>64</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1013</id>
          <x>64</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1014</id>
          <x>96</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1015</id>
          <x>128</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1016</id>
          <x>160</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1018</id>
          <x>192</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1019</id>
          <x>96</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1020</id>
          <x>128</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1021</id>
          <x>160</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1023</id>
          <x>192</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1024</id>
          <x>256</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1025</id>
          <x>256</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1026</id>
          <x>256</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1027</id>
          <x>256</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1028</id>
          <x>256</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1029</id>
          <x>256</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1030</id>
          <x>256</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1031</id>
          <x>256</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1032</id>
          <x>256</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1033</id>
          <x>256</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1059</id>
          <x>288</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1060</id>
          <x>320</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1061</id>
          <x>352</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1062</id>
          <x>384</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1063</id>
          <x>416</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1064</id>
          <x>448</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1065</id>
          <x>480</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1066</id>
          <x>512</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1067</id>
          <x>544</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1068</id>
          <x>544</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1069</id>
          <x>544</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1070</id>
          <x>544</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1071</id>
          <x>544</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1072</id>
          <x>544</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1073</id>
          <x>544</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1074</id>
          <x>544</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1075</id>
          <x>544</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1077</id>
          <x>544</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1079</id>
          <x>608</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1080</id>
          <x>608</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1086</id>
          <x>608</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1087</id>
          <x>608</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1088</id>
          <x>608</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1089</id>
          <x>608</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1091</id>
          <x>608</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1092</id>
          <x>608</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1093</id>
          <x>608</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1094</id>
          <x>640</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1095</id>
          <x>672</x>
          <y>32</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1096</id>
          <x>672</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1097</id>
          <x>704</x>
          <y>64</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1098</id>
          <x>704</x>
          <y>96</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1109</id>
          <x>800</x>
          <y>288</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1110</id>
          <x>800</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1111</id>
          <x>768</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1112</id>
          <x>736</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1113</id>
          <x>704</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1114</id>
          <x>672</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1117</id>
          <x>608</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1118</id>
          <x>640</x>
          <y>320</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1119</id>
          <x>800</x>
          <y>256</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1120</id>
          <x>800</x>
          <y>224</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1121</id>
          <x>736</x>
          <y>128</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1122</id>
          <x>768</x>
          <y>160</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1123</id>
          <x>800</x>
          <y>192</y>
          <obj>ObjWall</obj>
        </SerializeableRoomObject>
        <SerializeableRoomObject>
          <id>R2INST1124</id>
          <x>768</x>
          <y>288</y>
          <obj>ObjPlayer</obj>
        </SerializeableRoomObject>
      </objects>
      <enableViews>false</enableViews>
      <views>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
        <SerializeableRoomView>
          <visible>false</visible>
          <x>0</x>
          <y>0</y>
          <width>640</width>
          <height>480</height>
          <portX>0</portX>
          <portY>0</portY>
          <portWidth>640</portWidth>
          <portHeight>480</portHeight>
          <objFollow />
          <followHBor>32</followHBor>
          <followVBor>32</followVBor>
          <followHSp>-1</followHSp>
          <followVSp>-1</followVSp>
        </SerializeableRoomView>
      </views>
    </SerializeableGameItem>
  </items>
  <userAssemblies />
  <treeMainNodes>
    <SerializeableGameProjectTreeNode>
      <name>Sprites</name>
      <nodes>
        <SerializeableGameProjectTreeNode>
          <name>SprPlayer</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameSprite</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>SprWall</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameSprite</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>SprSpikes</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameSprite</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>SprKey</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameSprite</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>SprPortal</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameSprite</type>
        </SerializeableGameProjectTreeNode>
      </nodes>
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GameSprite</type>
    </SerializeableGameProjectTreeNode>
    <SerializeableGameProjectTreeNode>
      <name>Sounds</name>
      <nodes>
        <SerializeableGameProjectTreeNode>
          <name>BgMusic</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameSound</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>SomeSnd</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameSound</type>
        </SerializeableGameProjectTreeNode>
      </nodes>
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GameSound</type>
    </SerializeableGameProjectTreeNode>
    <SerializeableGameProjectTreeNode>
      <name>Backgrounds</name>
      <nodes />
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GameBackground</type>
    </SerializeableGameProjectTreeNode>
    <SerializeableGameProjectTreeNode>
      <name>Paths</name>
      <nodes>
        <SerializeableGameProjectTreeNode>
          <name>Path0</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GamePath</type>
        </SerializeableGameProjectTreeNode>
      </nodes>
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GamePath</type>
    </SerializeableGameProjectTreeNode>
    <SerializeableGameProjectTreeNode>
      <name>Scripts</name>
      <nodes>
        <SerializeableGameProjectTreeNode>
          <name>Global</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameScript</type>
        </SerializeableGameProjectTreeNode>
      </nodes>
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GameScript</type>
    </SerializeableGameProjectTreeNode>
    <SerializeableGameProjectTreeNode>
      <name>Fonts</name>
      <nodes>
        <SerializeableGameProjectTreeNode>
          <name>Font0</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameFont</type>
        </SerializeableGameProjectTreeNode>
      </nodes>
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GameFont</type>
    </SerializeableGameProjectTreeNode>
    <SerializeableGameProjectTreeNode>
      <name>Objects</name>
      <nodes>
        <SerializeableGameProjectTreeNode>
          <name>ObjPlayer</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameObject</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>ObjWall</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameObject</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>ObjSpikes</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameObject</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>ObjKey</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameObject</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>ObjPortal</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameObject</type>
        </SerializeableGameProjectTreeNode>
      </nodes>
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GameObject</type>
    </SerializeableGameProjectTreeNode>
    <SerializeableGameProjectTreeNode>
      <name>Rooms</name>
      <nodes>
        <SerializeableGameProjectTreeNode>
          <name>Room0</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameRoom</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>Room1</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameRoom</type>
        </SerializeableGameProjectTreeNode>
        <SerializeableGameProjectTreeNode>
          <name>RmEnd</name>
          <isFolder>false</isFolder>
          <type>ArcadeMaker.IDE.Items.GameRoom</type>
        </SerializeableGameProjectTreeNode>
      </nodes>
      <isFolder>true</isFolder>
      <type>ArcadeMaker.IDE.Items.GameRoom</type>
    </SerializeableGameProjectTreeNode>
  </treeMainNodes>
  <textureAtlasMap>
    <AtlasFilePath>C:\Users\איתן\Desktop\testgp1\res\atlases\main.png</AtlasFilePath>
    <Items>
      <Item>
        <SpriteName>SprPlayer</SpriteName>
        <ImageIndex>0</ImageIndex>
        <X>0</X>
        <Y>0</Y>
        <W>32</W>
        <H>32</H>
      </Item>
      <Item>
        <SpriteName>SprPlayer</SpriteName>
        <ImageIndex>1</ImageIndex>
        <X>0</X>
        <Y>32</Y>
        <W>32</W>
        <H>32</H>
      </Item>
      <Item>
        <SpriteName>SprWall</SpriteName>
        <ImageIndex>0</ImageIndex>
        <X>32</X>
        <Y>0</Y>
        <W>32</W>
        <H>32</H>
      </Item>
      <Item>
        <SpriteName>SprSpikes</SpriteName>
        <ImageIndex>0</ImageIndex>
        <X>32</X>
        <Y>32</Y>
        <W>32</W>
        <H>32</H>
      </Item>
      <Item>
        <SpriteName>SprKey</SpriteName>
        <ImageIndex>0</ImageIndex>
        <X>64</X>
        <Y>0</Y>
        <W>32</W>
        <H>32</H>
      </Item>
      <Item>
        <SpriteName>SprPortal</SpriteName>
        <ImageIndex>0</ImageIndex>
        <X>32</X>
        <Y>64</Y>
        <W>32</W>
        <H>32</H>
      </Item>
    </Items>
  </textureAtlasMap>
</SerializeableGameProject>